### ISSUE TITLE
pandas >= 0.23.0 required

### ISSUE THREAD

**Issue by SimonLarsen** [shfong/nbgwas#13]
The sort-argument was added to `pandas.concat` in version 0.23.0. The `pandas` dependency should be replaced with `pandas>=0.23.0` in setup.py.

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html

https://github.com/shfong/nbgwas/blob/00e75fc4154b3504d790b253bb96f0f369204194/nbgwas/tables.py#L406

**Comment by shfong** [comment]
Thanks for catching that. I've updated it.
