### ISSUE TITLE
Cytoscape lacks gene names

### ISSUE THREAD

**Issue by robd02130** [shfong/nbgwas#18]
Thanks for getting this package together. We are using it for analysis of screen data. Anyway, everything works well except when Cytoscape (3.7.1) is evoked with CyRest the Gene name is not shown. Index number is present instead.

**Comment by shfong** [comment]
I'll need to ask our Cytoscape developers to see how we can address this. Let me get back to you on this. 

Thanks,

Samson.

**Comment by shfong** [comment]
I added a `force_add_nodename` keyword argument to `view_in_cytoscape`. This adds an extra node attribute before it pushes the network Cytoscape. 

I'm not sure why the node names were being ignored earlier, but this should get around the issue for now.
